### PR TITLE
feat: [WD-14392] Add tests for instance upload.

### PR DESCRIPTION
**Pull request by Kxiru**
## Done

- Added Upload an instance, test.

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @mas-who or @edlerd for access.
    - With a local copy of this branch, [build and run as described in the docs](../CONTRIBUTING.md#setting-up-for-development).
2. Perform the following QA steps:
    - Run tests locally in dev environment.
    
## Screenshots

N/A

### CODE REVIEW

**Comment by Kxiru** [comment]
@edlerd Hallo!
Please could you refer me to an example of uploading an instance file to the e2e test via github actions for reference?

**Comment by edlerd** [comment]
> @edlerd Hallo! Please could you refer me to an example of uploading an instance file to the e2e test via github actions for reference?

I think once [this PR](https://github.com/canonical/lxd-ui/pull/872) is merged, we can do the same as for images: 1. export an instance, 2. import that instance from the file produced in 1.

**Comment by Kxiru** [comment]
> > @edlerd Hallo! Please could you refer me to an example of uploading an instance file to the e2e test via github actions for reference?
> 
> I think once [this PR](https://github.com/canonical/lxd-ui/pull/872) is merged, we can do the same as for images: 1. export an instance, 2. import that instance from the file produced in 1.

Sounds good. Does that mean that this issue/PR is blocked for now?

**Comment by edlerd** [comment]
> Sounds good. Does that mean that this issue/PR is blocked for now?

Yes, best to postpone it until unblocked.

**Review by edlerd — APPROVED** [review]
LGTM :+1:

**Pull request merged**
