### PR TITLE
Remove ticls report upload to prevent a security issue

### PR DESCRIPTION
**Pull request by edlerd**
## Done

- Remove ticls report upload to prevent a security issue

### CODE REVIEW

**Review by mas-who — APPROVED** [review]
What's the context for this PR? Is the security issue originating from TICS or the content of the report we are uploading?

**Comment by aaryanporwal** [comment]
ticls -> tics. I know the typo is way funnier

**Comment by edlerd** [comment]
> What's the context for this PR? Is the security issue originating from TICS or the content of the report we are uploading?

The debug report includes some sensitive information.

**Comment by Kxiru** [comment]
LGMT! Good spot :)

**Pull request merged**
