### PR TITLE
Use en-gb date language locale for snapshot expiry form

### PR DESCRIPTION
**Pull request by edlerd**
## Done

- fixed the date format on the expiry input for snapshot creation

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @lorumic or @edlerd for access.
    - With a local copy of this branch, run as described in the [Readme](https://github.com/canonical/lxd-ui#setting-up-for-development).
2. Perform the following QA steps:
    - check snapshot creation/edit date picker

### CODE REVIEW

**Comment by lorumic** [comment]
What's the rationale behind forcing a locale to every user in the world?

**Comment by edlerd** [comment]
> What's the rationale behind forcing a locale to every user in the world?

I didn't realize my setting is not UK English. I guess then it's better to keep this adopting to user prefs than setting the language for all.

**Comment by lorumic** [comment]
> I didn't realize my setting is not UK English. I guess then it's better to keep this adopting to user prefs than setting the language for all.

Sorry, I don't get this. What's the problem of having one's own local date format displayed here?

**Comment by edlerd** [comment]
> > I didn't realize my setting is not UK English. I guess then it's better to keep this adopting to user prefs than setting the language for all.
> 
> Sorry, I don't get this. What's the problem of having one's own local date format displayed here?

I meant this should be closed, because adopting to the locale setting is preferred. Just a previous confusion on my browsers locale (which was us, hence opening the PR, but setting it to uk is the better fix).

**Pull request closed without merging**
