### PR TITLE
fix: merge playwright reports with assets

### PR DESCRIPTION
**Pull request by mas-who**
## Done

- Fixed issue where assets (videos/traces) are not attached to the html playwright report

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @lorumic or @edlerd for access.
    - With a local copy of this branch, run as described [here](../HACKING.md#setting-up-for-development).
2. Perform the following QA steps:
    - Ensure CI passes
    - Ensure videos and traces are in failing tests

### CODE REVIEW

**Review by edlerd — APPROVED** [review]
LGTM

**Comment by edlerd** [comment]
Thanks for fixing, the video looks good now in [this report](https://canonical.github.io/lxd-ui/reports/pr-660/7972395670/1/#?testId=e8e6866b70fb8a71d6de-29e8ebbfd84c7335a69f50aee4a87af1e5a5). Though, the trace is missing some styles (In the report click on retry #1, then on the trace).

**Comment by mas-who** [comment]
> Thanks for fixing, the video looks good now in [this report](https://canonical.github.io/lxd-ui/reports/pr-660/7972395670/1/#?testId=e8e6866b70fb8a71d6de-29e8ebbfd84c7335a69f50aee4a87af1e5a5). Though, the trace is missing some styles (In the report click on retry #1, then on the trace).

Yeah that's a strange one, I see the css styling is just missing in the gh-pages branch. The executed playwright commands and folder structure is exactly the same now between my local environment and runner environment. Maybe it's the node version, going to see if bumping it up to v20 works.

**Review by edlerd — APPROVED** [review]
QA and code looks good. :+1:

**Pull request merged**
