### PR TITLE
Fix navigation toggle and logo are sticky WD-2987

### PR DESCRIPTION
**Pull request by edlerd**
## Done

- fix navigation on small height screens
- avoid overlaying the logo with the project selector
- make the navigation toggle at the bottom sticky

Fixes WD-2987

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @lorumic or @edlerd for access.
    - With a local copy of this branch, run as described in the [Readme](https://github.com/canonical/lxd-ui#setting-up-for-development).
2. Perform the following QA steps:
    - test navigation on all possible screen dimensions

### CODE REVIEW

**Comment by lorumic** [comment]
The toggle "jumps up" the external links on large screens:

Peek 2023-03-31 11-38

**Comment by edlerd** [comment]
> The toggle "jumps up" the external links on large screens:

Right, I didn't test the large bit, now it should work smoothly.

**Comment by al-bakalova** [comment]
The problem seems to still be there @edlerd 
Screenshot 2023-03-31 at 15 06 07

**Comment by edlerd** [comment]
Will have another look. Maybe will have to buy a bigger monitor in between :D

**Comment by edlerd** [comment]
The problem was with the non-x-large screens. Now it works on all dimensions.

**Comment by al-bakalova** [comment]
Looks good to me! Danke!

**Comment by lorumic** [comment]
I see that it gets sometime clipped by the scrollbar:

image

I wonder if we should increase its distance from the right edge? :thinking:

**Comment by al-bakalova** [comment]
Maybe we can try to align the collapse/expand button with the edge of the project switch field?

**Comment by edlerd** [comment]
> Maybe we can try to align the collapse/expand button with the edge of the project switch field?

did that.

**Review by lorumic — APPROVED** [review]

**Pull request merged**
