### PR TITLE
Set a min- and max-height for cloud-init config fields

### PR DESCRIPTION
**Pull request by lorumic**

### CODE REVIEW

**Comment by lorumic** [comment]
Now that #240 is merged, this can also be reviewed. @al-bakalova @edlerd

**Comment by edlerd** [comment]
The read mode is missing the height constraints. It comes in with the [code renderer](https://github.com/canonical/lxd-ui/blob/main/src/pages/instances/forms/CloudInitForm.tsx#L31)

**Comment by lorumic** [comment]
> The read mode is missing the height constraints. It comes in with the [code renderer](https://github.com/canonical/lxd-ui/blob/main/src/pages/instances/forms/CloudInitForm.tsx#L31). An example on the demo server is [here](https://lxd-ui-249.demos.haus/ui/default/profiles/detail/new-profile-name/configuration).

Right - well spotted. Should be good now.

**Review by edlerd — APPROVED** [review]
Thanks for changes, lgtm

**Comment by al-bakalova** [comment]
Looks good to me. I'd like to clarify one point though:
- Why do we get line numbers only for the first three lines? It looks kind of broken to me. Is this expected?

Screenshot 2023-03-30 at 10 40 39

**Comment by al-bakalova** [comment]
@lorumic It all makes sense! Thanks for clarifying this, Michele!

**Pull request merged**
