### PR TITLE
Update images

### PR DESCRIPTION
**Pull request by edlerd**
## Done

- changed image order to be ubuntu images from newest to oldes with lts on top
- added image update script
- updated images (in draft, because of the pending release of lunar lobster)

## QA

1. Run the LXD-UI:
    - On the demo server via the link posted by @webteam-app below. This is only available for PRs created by collaborators of the repo. Ask @lorumic or @edlerd for access.
    - With a local copy of this branch, run as described in the [Readme](https://github.com/canonical/lxd-ui#setting-up-for-development).
2. Perform the following QA steps:
    - check image list for creating instances

### CODE REVIEW

**Review by lorumic — COMMENTED** [review]
```
~/dev/lxd-ui$ scripts/update-images.sh 
scripts/update-images.sh: line 3: jq: command not found
```
This is what I get if I try to run the script in my environment. Maybe we should refrain from including in the project something that is unlikely to work without additional effort?
Or is the script there for reference only? Ideally, what I would expect here would be:

- the JSON files are empty (or non-existent) in the project by default
- the script is run automatically with the `dotrun` command

Currently what we have is a script "for reference", that cannot work unless you have `jq` installed, and pre-filled JSON files.

**Comment by edlerd** [comment]
> Currently what we have is a script "for reference", that cannot work unless you have `jq` installed, and pre-filled JSON files.

The script is there to have it shared to make it easier to update the images in the future. I can also remove it and just keep a local copy. Wdyt?

**Comment by lorumic** [comment]
> The script is there to have it shared to make it easier to update the images in the future. I can also remove it and just keep a local copy. Wdyt?

I think having the script is good, but ideally I would like to see it run automatically at every project run, so that basically what we achieve is an automatic check of the images, and always have the most up-to-date version available in the app. Would that be a feasible and good idea?

**Comment by edlerd** [comment]
> I think having the script is good, but ideally I would like to see it run automatically at every project run, so that basically what we achieve is an automatic check of the images, and always have the most up-to-date version available in the app. Would that be a feasible and good idea?

I am afraid to make the build more complex. Because we'll add the dependency to the image servers for a successful build. I think it is more reliable if we update it manually and keep track in git.
Though I'll add a check to the script to warn in case jq is not installed.

**Review by lorumic — APPROVED** [review]

**Pull request merged**
