### PR TITLE
Adjusted design of the terminal tab [WD-2553]

### PR DESCRIPTION
**Pull request by lorumic**
- Moved "Reconnect" button inside the tab
- Moved notifications inside the tab
- Made header, notification rows and control row sticky - only terminal is to be scrollable
- Adjusted terminal's background colour

### CODE REVIEW

**Review by edlerd — COMMENTED** [review]
LGTM, there is one visual bug with the scrollbar of the terminal, to reproduce:
* make the browser window small
* hit enter ~40 times
* maximize browser window
It sometimes happens, but not always. I assume this is some race condition in play with with resize / re-render.

**Comment by al-bakalova** [comment]
Good job, @lorumic! Looks good to me.

**Comment by lorumic** [comment]
> LGTM, there is one visual bug with the scrollbar of the terminal, to reproduce:
> 
> * make the browser window small
> * hint enter ~40 times
> * maximize browser window
>   It sometimes happens, but not always. I assume this is some race condition in play with with resize / re-render.

What's happening exactly? I cannot see anything strange on the scrollbar trying the steps that you listed. Also, on which browser(s) did you experience this?

**Comment by edlerd** [comment]
> What's happening exactly? I cannot see anything strange on the scrollbar trying the steps that you listed. Also, on which browser(s) did you experience this?

It gets a little distorted, I can post a picture tomorrow or share it with you. I could reproduce it when making the window quite small and then maximizing it. Interestingly, when changing the size slowly it didn't happen, and it also fixed itself when resizing slowly..

**Comment by lorumic** [comment]
> It gets a little distorted, I can post a picture tomorrow or share it with you. I could reproduce it when making the window quite small and then maximizing it. Interestingly, when changing the size slowly it didn't happen, and it also fixed itself when resizing slowly.

Ok, anyway it doesn't sound like something we should really worry about, given that it's so hard to reproduce (and notice), or does it?

**Comment by lorumic** [comment]
@edlerd Added the `setTimeout` fix as discussed, you can proceed with the review when you have time.

**Review by edlerd — APPROVED** [review]

**Pull request merged**
